name: Run tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3, 3.4]
    continue-on-error: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
